[book]
authors = ["Jinzhou Zhang"]
language = "zh"
multilingual = false
src = "src"
title = "Java G1GC 小册子"

[preprocessor.fix-cjk-spacing]
command = "mdbook-fix-cjk-spacing"

[output.html]
mathjax-support = true
google-analytics = "UA-39956831-2"
additional-css = ["css/lotabout.css"]

[output.html.search]
enable = false
