[book]
authors = ["Jinzhou Zhang"]
language = "zh"
multilingual = false
src = "src"
title = "Java 并发知识"

[preprocessor.fix-cjk-spacing]
command = "mdbook-fix-cjk-spacing"

[output.html]
mathjax-support = true
additional-css = ["css/lotabout.css"]
