# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the source branch
  push:
    branches: [ source ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: '>=14'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install hexo
        run: |
          npm install -g hexo-cli
          npm install -g gitbook-cli

      - name: install dependencies
        run: npm install
      - name: build
        run: |
          git submodule init
          git submodule update
          hexo -V
          hexo generate --debug
          ./ci/build-books.sh

          export INDEX_CHARS=$(wc -c public/index.html | awk '{print $1}')
          echo $INDEX_CHARS
          if ! [[ $INDEX_CHARS > 0 ]]; then
              echo "error on build, index.html is empty"
              exit 1
          fi

      - name: patch config for deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Jinzhou Zhang"
          git config --global user.email "lotabout@gmail.com"
          echo "${GH_TOKEN}-ex" | cut -c 1-3
          sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml

      - name: deploy
        run: |
          hexo deploy --silent
